### ISSUE TITLE
Webpage not completing on Safari

### ISSUE THREAD

**Issue by timisenman** [rootvc/cli-website#80]
From a mac, running Sonoma 14.2.1 (23C71), using Safari (Version 17.2.1 (19617.1.17.11.12)), the webpage didn't resolve to show the terminal's text field. It loaded correctly on other browsers (in my case, Arc).

Congrats on the new fund!

**Comment by kanetronv2** [comment]
Interesting, I can't seem to replicate it! any other environmental
variables?

**Comment by kanetronv2** [comment]
closing bc couldn't replicate
